---
abstract: 'Multipart HTML Email builder'
author:
  - 'British Broadcasting Corporation'
  - 'Tony Hennessy'
  - 'Simon Flack'
  - 'John Alden <cpan _at_ bbc _dot_ co _dot_ uk>'
  - 'Ricardo Signes <rjbs@cpan.org>'
  - 'Henry Van Styn <vanstyn@cpan.org>'
build_requires:
  Email::Send: 0
  File::Copy: 0
  File::Slurp: 0
  Test::Assertions::TestScript: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.140640'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Email-MIME-CreateHTML
requires:
  Carp: 0
  Data::Serializer: 0
  Email::MIME: 0
  Email::MIME::Creator: 0
  Exporter: 0
  File::Slurp::WithinPolicy: 0
  File::Spec: 0
  HTML::Tagset: 0
  HTML::TokeParser::Simple: 3.15
  LWP::UserAgent: 0
  Log::Trace: 0
  MIME::Types: 0
  Scalar::Util: 0
  Test::Assertions: 0
  Test::Assertions::TestScript: 0
  URI::Escape: 0
  URI::WithBase: 0
  URI::file: 0
  strict: 0
  vars: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Email-MIME-CreateHTML
  repository: https://github.com/vanstyn/Email-MIME-CreateHTML.git
version: 1.040
