--- #YAML:1.0
name:               Email-MIME-CreateHTML
version:            1.030
abstract:           Multipart HTML Email builder
author:
    - British Broadcasting Corporation
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Serializer:     0
    Email::MIME::Creator:  0
    File::Slurp::WithinPolicy:  0
    HTML::Tagset:         0
    HTML::TokeParser::Simple:  3.15
    Log::Trace:           0
    MIME::Types:          0
    Test::Assertions:     0
    Test::Assertions::TestScript:  0
no_index:
    package:
        - Email::MIME
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
